export const GET_LIST = "GET_LIST"
export const EDIT_LIST = "EDIT_LIST"
export const SELECT = "SELECT"
export const DELETE_ELEMENT = "DELETE_ELEMENT"
export const SET_MAP = "SET_MAP"
export const ADD_TO_TABLE = "ADD_TO_TABLE"
export const PUT_DATA_MAP = "PUT_DATA_MAP"
export const GET_SEARCH_LIST = "GET_SEARCH_LIST"
export const MOUSE_DOWN = "MOUSE_DOWN"
export const X_START = "X_START"
export const SET_BORDER = "SET_BORDER"
export const SET_START_BORDER = "SET_START_BORDER"
export const SET_EDITED = "SET_EDITED"

export const SELECT_SAGA = "SELECT_SAGA"
export const PUT_SAGA = "PUT_SAGA"
export const EDIT_SAGA = "EDIT_SAGA"
export const SEARCH_LIST_SAGA = "SEARCH_LIST_SAGA"